### ISSUE TITLE
Facebook sometimes doesn't have an image

### ISSUE THREAD

**Issue by eads** [nprapps/graeae#100]
Dammit!

```
[cron-staging.nprapps.org] Executing task 'cron_jobs.scrape_facebook'
Traceback (most recent call last):
  File "/home/ubuntu/apps/graeae/virtualenv/local/lib/python2.7/site-packages/fabric/main.py", line 717, in main
    *args, **kwargs
  File "/home/ubuntu/apps/graeae/virtualenv/local/lib/python2.7/site-packages/fabric/tasks.py", line 299, in execute
    multiprocessing
  File "/home/ubuntu/apps/graeae/virtualenv/local/lib/python2.7/site-packages/fabric/tasks.py", line 198, in _execute
    return task.run(*args, **kwargs)
  File "/home/ubuntu/apps/graeae/virtualenv/local/lib/python2.7/site-packages/fabric/tasks.py", line 112, in run
    return self.wrapped(*args, **kwargs)
  File "/home/ubuntu/apps/graeae/repository/fabfile/cron_jobs.py", line 42, in scrape_facebook
    scraper.write(db, posts, insights)
  File "/home/ubuntu/apps/graeae/repository/scrapers/facebook/scraper.py", line 77, in write
    row = post.serialize()
  File "/home/ubuntu/apps/graeae/repository/scrapers/facebook/models.py", line 26, in serialize
    ('art_url', self.art_url),
  File "/home/ubuntu/apps/graeae/repository/scrapers/facebook/models.py", line 74, in art_url
    url = self.api_post['picture']
KeyError: 'picture'
```

**Comment by eads** [comment]
fixed in 80e0a7d3c3f4330b27f3c3931e9fb602f4937150
